import "./globals.css";
import { Roboto, Playball } from "next/font/google";

export const metadata = {
    title: "Rono Koushique",
    description: "Generated by create next app",
};

const roboto = Roboto({
    weight: ["100", "400", "300", "500", "700", "900"],
    subsets: ["latin"],
    variable: "--font-roboto",
});

const playball = Playball({
    weight: ["400"],
    subsets: ["latin"],
    variable: "--font-playball",
});

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`${roboto.variable} ${playball.variable} bg-neutral-950`}
            >
                {children}
            </body>
        </html>
    );
}
