export const metadata = {
    title: "Rono Koushique",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return <main className="bg-neutral-950">{children}</main>;
}
